### ISSUE TITLE
package name formatting

### ISSUE THREAD

**Issue by topepo** [tidymodels/TMwR#35]
To backtick or not...? 

How about something like

```css
span.pkg {
  color: #0066CC;  
  font-family: monospace;
}
```

(we can pick better options than ☝️ )

![image](https://user-images.githubusercontent.com/5731043/90024939-792c6300-dc83-11ea-884c-3c679e4f6b4e.png)
